# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a200tfbg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sudeep/Documents/Project-GITHUB/CORDIC_Unit/vivado/CORDIC/CORDIC.cache/wt [current_project]
set_property parent.project_path /home/sudeep/Documents/Project-GITHUB/CORDIC_Unit/vivado/CORDIC/CORDIC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  /home/sudeep/Documents/Project-GITHUB/CORDIC_Unit/Design_files/correction.v
  /home/sudeep/Documents/Project-GITHUB/CORDIC_Unit/Design_files/add_sub.v
  /home/sudeep/Documents/Project-GITHUB/CORDIC_Unit/Design_files/CORDIC_UNIT.v
}
catch { write_hwdef -file CORDIC_UNIT.hwdef }
synth_design -top CORDIC_UNIT -part xc7a200tfbg676-2
write_checkpoint -noxdef CORDIC_UNIT.dcp
catch { report_utilization -file CORDIC_UNIT_utilization_synth.rpt -pb CORDIC_UNIT_utilization_synth.pb }
